using './app.bicep'

param location = readEnvironmentVariable('ABDA_DEPLOY_LOCATION', 'eastus2')
param appName = readEnvironmentVariable('ABDA_DEPLOY_APP_NAME', 'abda-nl-web')
param containerAppsEnvironmentName = readEnvironmentVariable('ABDA_DEPLOY_ENVIRONMENT_NAME')
param registryName = readEnvironmentVariable('ABDA_DEPLOY_REGISTRY_NAME')
param pullIdentityName = readEnvironmentVariable('ABDA_DEPLOY_PULL_IDENTITY_NAME')
param image = readEnvironmentVariable('ABDA_DEPLOY_IMAGE')
param customHostname = readEnvironmentVariable('ABDA_DEPLOY_CUSTOM_HOSTNAME', '')
param customDomainCertificateId = readEnvironmentVariable('ABDA_DEPLOY_CUSTOM_DOMAIN_CERTIFICATE_ID', '')
param oidcMetadataUrl = readEnvironmentVariable('ABDA_DEPLOY_OIDC_METADATA_URL')
param oidcIssuer = readEnvironmentVariable('ABDA_DEPLOY_OIDC_ISSUER')
param oidcClientId = readEnvironmentVariable('ABDA_DEPLOY_OIDC_CLIENT_ID')
param foundryEndpoint = readEnvironmentVariable('ABDA_DEPLOY_FOUNDRY_ENDPOINT')
param foundryClaudeDeployment = readEnvironmentVariable('ABDA_DEPLOY_CLAUDE_DEPLOYMENT', 'claude-sonnet-4-6')
param postgresHost = readEnvironmentVariable('ABDA_DEPLOY_POSTGRES_HOST')
param postgresAppLogin = readEnvironmentVariable('ABDA_DEPLOY_POSTGRES_APP_LOGIN', 'abda_app')
param postgresAppPassword = readEnvironmentVariable('ABDA_DEPLOY_POSTGRES_APP_PASSWORD')
param sessionSecret = readEnvironmentVariable('ABDA_DEPLOY_SESSION_SECRET')
param mcpTokenPepper = readEnvironmentVariable('ABDA_DEPLOY_MCP_TOKEN_PEPPER')
param metricsToken = readEnvironmentVariable('ABDA_DEPLOY_METRICS_TOKEN')
param oidcClientSecret = readEnvironmentVariable('ABDA_DEPLOY_OIDC_CLIENT_SECRET')
param foundryApiKey = readEnvironmentVariable('ABDA_DEPLOY_FOUNDRY_API_KEY')
param openrouterApiKey = readEnvironmentVariable('ABDA_DEPLOY_OPENROUTER_API_KEY')
param openrouterBudgetMicrousd = int(readEnvironmentVariable('ABDA_DEPLOY_OPENROUTER_BUDGET_MICROUSD', '500000000'))
